//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Shop_Category> T_Shop_Category { get; set; }
        public virtual DbSet<T_Shop_Product> T_Shop_Product { get; set; }
        public virtual DbSet<T_Base_User> T_Base_User { get; set; }
        public virtual DbSet<T_Base_Address> T_Base_Address { get; set; }
        public virtual DbSet<T_Shop_Cart> T_Shop_Cart { get; set; }
    }
}
