//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Shop_Product()
        {
            this.T_Shop_Cart = new HashSet<T_Shop_Cart>();
            this.T_Shop_Order = new HashSet<T_Shop_Order>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string PicUrl { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> StockAmount { get; set; }
        public Nullable<int> SelledAmount { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual T_Shop_Category T_Shop_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Shop_Cart> T_Shop_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Shop_Order> T_Shop_Order { get; set; }
    }
}
