//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string PicUrl { get; set; }
        public string price { get; set; }
        public Nullable<int> StockAmount { get; set; }
        public Nullable<int> SelledAmount { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual T_Shop_Category T_Shop_Category { get; set; }
    }
}
